# Generated by Django 5.0.2 on 2024-03-15 04:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_time', models.TimeField(blank=True, null=True)),
                ('total_purchased_amount', models.IntegerField(blank=True, null=True)),
                ('purchase_slip', models.ImageField(blank=True, null=True, upload_to='purchase_slips/')),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.buyer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('balance_amount', models.IntegerField(blank=True, null=True)),
                ('new_payment', models.IntegerField(blank=True, null=True)),
                ('balance_paid_date', models.DateField(auto_now=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('upi', 'UPI'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20, null=True)),
                ('other_payment_text', models.TextField(blank=True, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('payment_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('dispatch_through', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=200, null=True)),
                ('transportation', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.purchase')),
            ],
        ),
    ]
