# Generated by Django 5.0.2 on 2024-02-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_balance_amount_paid_payment_new_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='new_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
